<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html> 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>MBARI Expeditions</title>
<link rel="stylesheet" type="text/css" href="/expd/styles/expd_karen.css">
<script language="JavaScript" type="text/javascript">
<!-- hide from old browsers

function OpenData(url,type) 
{
   
  if (navigator.appVersion.indexOf("(X11") != -1 || navigator.appVersion.indexOf("(Mac") != -1) {
	if (type == "frameGrabs") {
		var win = window.open(url, type, "menubar=yes,toolbar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes");
	}
	else if (type == "logrparse") {
		var win = window.open(url, type, "menubar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes,width=500,height=300");
	}
	else {
		var win = window.open(url, type, "menubar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes");
	}
  }
  else {
    if (type == "frameGrabs" || type == "digitalImages") {
		var win = window.open(url, type, "menubar=yes,toolbar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes");
	}
	else if (type == "logrparse") {
		var win = window.open(url, type, "menubar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes,width=500,height=300");
	}
	else {
		//var win = window.open(url, type, "menubar=yes,alwaysRaised=yes,location=yes,status=1,scrollbars=yes,resizable=yes");
		var win = window.open(url, type);
	}
  }
}

// -->
</script>
</head>
<body bgcolor="#FFFFFF">
<table border="0" cellpadding="5" width="680">
<tr>
<td valign="top" width="20%">
<a href="http://mww.mbari.org">
<img src="/expd/log/images/mbarilogo-120_sh.gif" border="0" width="120" height="70"></a>
</td>
<td valign="top" width="80%">