
<p class="smalltext" align="center">
&middot;
<br>
<a href=/expd/queries/viewExpd.kml>Query from Google Earth</a>
&middot;
<a href=waypoint_telepresence.asp>Waypoint management</a>
&middot;
<a href="http://mww2.shore.mbari.org/events/calendar.cgi">Web calendar</a>
&middot;
<a href="/3Dreplay/3Dterrain_telepresence.asp">Dives over terrain</a>
&middot;
<a href="precruise_telepresence.asp">Precruise entry</a>
&middot;
<a href="postcruise_telepresence.asp">Keyword search</a>
&middot;
<a href="postcruise_telepresence.asp?search=advanced">Advanced search</a>
&middot;
<a href="default_telepresence.asp">Administrative page</a>
&middot;
<a href="http://www.mbari.org/dmo/cruise_planning/cruise.htm">Cruise planning &amp; scheduling</a>
&middot;
<a href="/itd/video/ShipProcedures/index.htm">Shipboard video procedures</a>
&middot;
<a href="/samplesDB/Queries/">Samples Database</a>
&middot;
<a href="http://tramontane2.shore.mbari.org/expd/log/tapeSummary_telepresence.asp?step=QueryForm">Video Media</a>
</p>

<hr><font size="2">
Expedition DB maintenance team: </font>
<font size="2" color="#408080">
	<a href="mailto:mccann@mbari.org" style="color:#408080">Mike McCann</a>, 
	<a href="mailto:paje@mbari.org" style="color:#408080">Jenny Paduan</a>, 
	<a href="mailto:rich@mbari.org" style="color:#408080">Rich Schramm</a>, 
	<a href="mailto:mschultz@mbari.org" style="color:#408080">Matt Schultz</a>, 
	<a href="mailto:lonny@mbari.org" style="color:#408080">Lonny Lundsten</a> & 
	<a href="mailto:salamy@mbari.org" style="color:#408080">Karen Salamy</a>.
</font>

</body>
</html>