<table border="0" cellpadding="5" width="100%">
<tr>

<td valign=center width=20%>
<a href=http://www.mbari.org>
<img src=<% =Application("BaseURL") %>/images/mbarilogo-120_sh.gif border=0 height=70></a>
</td>

<td valign=center width=80%>
<center><b><font size=+3>MBARI Waypoint Management</font></b></center>
</td>

<td valign=center width=20%>
<a href=<% =Application("BaseURL") %>/waypoint_telepresence.asp>
<img src=<% =Application("BaseURL") %>/compassrose.jpg border=0 height=70></a>
</td>

</tr>
</table>
<br>